// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAquOxSF5PmASmSA1zEjWR1x_JYGFYCLUo',
    appId: '1:1022909081727:web:de71cbdabcc40ea685b74a',
    messagingSenderId: '1022909081727',
    projectId: 'vrc-waiver-app',
    authDomain: 'vrc-waiver-app.firebaseapp.com',
    storageBucket: 'vrc-waiver-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTVKeo_TTqgDiFsOm9dRZoJRfUP6KA7I',
    appId: '1:1022909081727:android:f29e5005ddc83a4185b74a',
    messagingSenderId: '1022909081727',
    projectId: 'vrc-waiver-app',
    storageBucket: 'vrc-waiver-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLykdNoYkddVNewwXPoVE40_O9AC7RYQ',
    appId: '1:1022909081727:ios:d7eaf28b0370144385b74a',
    messagingSenderId: '1022909081727',
    projectId: 'vrc-waiver-app',
    storageBucket: 'vrc-waiver-app.appspot.com',
    iosBundleId: 'com.example.vrcWaiverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCLykdNoYkddVNewwXPoVE40_O9AC7RYQ',
    appId: '1:1022909081727:ios:d7eaf28b0370144385b74a',
    messagingSenderId: '1022909081727',
    projectId: 'vrc-waiver-app',
    storageBucket: 'vrc-waiver-app.appspot.com',
    iosBundleId: 'com.example.vrcWaiverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAquOxSF5PmASmSA1zEjWR1x_JYGFYCLUo',
    appId: '1:1022909081727:web:260c8f7b1b4e591f85b74a',
    messagingSenderId: '1022909081727',
    projectId: 'vrc-waiver-app',
    authDomain: 'vrc-waiver-app.firebaseapp.com',
    storageBucket: 'vrc-waiver-app.appspot.com',
  );
}
